### ISSUE TITLE
Hitting java.lang.NullPointerException when trying to delete SQS messages

### ISSUE THREAD

**Issue by andrewcretin** [awslabs/aws-serverless-sqs-event-source#2]
Hello,

I've set everything up and the correct lambda function is being successfully executed. 
The SQSPoller logs indicate this success is received. `INFO MessageDispatcher:62 - Processed 10 messages in 1399ms. perMessageAverage=139ms`

Then it crashes before any messages can be removed from the SQS queue. It gives this stack trace 
```
java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
at com.amazonaws.serverless.sqseventsource.MessageDispatcher.dispatch(MessageDispatcher.java:52)
at com.amazonaws.serverless.sqseventsource.SQSPoller.poll(SQSPoller.java:39)
at com.amazonaws.serverless.sqseventsource.lambda.SQSPollerHandler.handleRequest(SQSPollerHandler.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```

Any help would be appreciated!

Thanks,
Andrew

**Comment by jlhood** [comment]
Hi Andrew. Sorry for the delayed response. The null pointer exception indicates the lambda function that processed the SQS messages didn't return the expected format. The README has a description of the result message format that the app is expecting:

https://github.com/awslabs/aws-serverless-sqs-event-source/blob/master/README.md#messageprocessor

If your message process lambda function is written in Java, this repo includes a library that handles the message format for you. In other languages, you need to make sure the JSON response you return from your lambda function is in the expected format.

Hope this helps!
